Documents/aoomuki competences version 3/Matrice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app_competences.urls')),

]


Documents/aoomuki competences version 3/app_competences/urls.py
from django.urls import path, re_path, include
from . import views
# from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import LoginView, LogoutView
# from rest_framework.routers import DefaultRouter
# from .api import UserViewSet, ProfilViewSet, FieldViewSet, CompetenceViewSet
# # from .views import PasswordsChangeView
# router = DefaultRouter()
# router.register(r'users', UserViewSet, basename='user')
# router.register(r'profils', ProfilViewSet, basename='profil')  
# router.register(r'fields', FieldViewSet, basename='field')
# router.register(r'competences', CompetenceViewSet, basename='competence')
app_name = 'matrice'

urlpatterns = [
    # path('api/', include(router.urls)),
    # path('Connexion/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='Connexion'),
    # path('Deconnexion/', auth_views.LogoutView.as_view(next_page='matrice:Connexion',template_name='registration/logout.html'), name='Deconnexion'),
    # path('mot_de_passe/', views.change_password, name='change_password'),
    path('', views.index, name='index'),
    path('Enregistrement/', views.register, name='Enregistrement'),

]

Documents/aoomuki competences version 3/app_competences/models.py
from django.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import (BaseUserManager, AbstractBaseUser)
from django.contrib.auth.models import UserManager

class Society(models.Model):
    name = models.CharField('Société', max_length=200, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Société"

class ListWorkStation(models.Model):
    name = models.CharField('nom', max_length=50, unique=True)
    commentary = models.CharField('commentaire', max_length=250, unique=False)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Liste postes de travail"
        
class Certification(models.Model):
    name = models.CharField('nom', max_length=200, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Certification"

class Field(models.Model):
    name = models.CharField('nom', max_length=200, unique=True)
    description = models.CharField('description', max_length=250, unique=False)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Domaine"

class Competence(models.Model):
    name = models.CharField('nom', max_length=50, unique=False)
    commentary = models.CharField('commentaire', max_length=250, unique=False)
    field = models.ForeignKey(Field,on_delete=models.CASCADE, null=True, default=1)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Compétence"

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(verbose_name='Adresse mail', max_length=255, unique=True)
    username = models.CharField(verbose_name='Nom d\'utilisateur',max_length=50, null=True, blank=True)
    last_name = models.CharField(verbose_name=' Nom',max_length=50)
    first_name = models.CharField(verbose_name='Prénom',max_length=50)
    is_active = models.BooleanField(verbose_name='Adresse mail',default=True)
    is_staff = models.BooleanField(verbose_name='Equipe ?',default=False)
    is_superuser = models.BooleanField(verbose_name='Superuser ?',default=False)
    is_collaborater = models.BooleanField(verbose_name='Collaborateur ?',default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    workstation = models.ForeignKey(ListWorkStation,on_delete=models.CASCADE,verbose_name='Poste', null=True)
    society = models.ForeignKey(Society,on_delete=models.CASCADE,verbose_name='Société', null=True)
    # notice the absence of a "Password field", that is built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','last_name', 'first_name'] # Email & Password are required by default.

    objects = UserManager() 

    # def get_full_name(self):
    #     # The user is identified by their email address
    #     return self.email

    # def get_short_name(self):
    #     # The user is identified by their email address
    #     return self.email

    # def __str__(self):
    #     return self.email

    # def has_perm(self, perm, obj=None):
    #     "L'utilisateur dispose-t-il d'une autorisation spécifique?"
    #     # Simplest possible answer: Yes, always
    #     return True

    # def has_module_perms(self, app_label):
    #     "L'utilisateur a-t-il les autorisations pour afficher l'application `app_label`?"
    #     # Simplest possible answer: Yes, always
    #     return True

    # @property
    # def is_staff(self):
    #     "L'utilisateur est-il membre du personnel?"
    #     return self.is_staff

    # @property
    # def is_admin(self):
    #     "L'utilisateur est-il un membre administrateur?"
    #     return self.is_admin

class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


Documents/aoomuki competences version 3/app_competences/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm, TextInput, EmailInput, FileInput, PasswordInput, Select, CheckboxInput,RadioSelect, CheckboxSelectMultiple
from django.forms.utils import ErrorList
from django import forms
from .models import Competence, Field, Certification, Society

from .models import User
# from .models import ListWorkstation, Society

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('is_collaborater', 'workstation', 'society',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('is_collaborater', 'workstation', 'society', )

class AddUserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["last_name", "first_name", "username", 'email', 'is_superuser', 'is_staff','is_collaborater', 'workstation', 'society']

Documents/aoomuki competences version 3/app_competences/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import AddUserForm

# from django.contrib import messages
# # from django.views.generic.list import ListView
# from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
# from .forms import AddUserForm, AddCollaboraterForm, AddFieldForm, AddCompetenceForm, AddCertificationForm, AddSocietyForm, ProfilForm, ModifyProfilForm, AddCompCollabForm, AddSocietyForm, ProfilFormUser
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth import update_session_auth_hash
# from django.contrib.auth.views import PasswordChangeView
# from django.urls import reverse_lazy
# class UserList(ListView):
  
#     # specify the model for list view
#     model = User
#     template_name = 'User_List.html'
    
def index(request):
    # users = User.objects.all()
    # context = { 'users':users}
    template = loader.get_template('app/index.html')
    return HttpResponse(template.render({}, request))

def register(request):
    form = AddUserForm()
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = form.save()
            messages.success(request,f'Bienvenue {username}, votre compte a été crée avec succés')
            return render(request, 'register.html', context)
            # return redirect('matrice:Liste_des_utilisateurs')
        else:
            messages.error(request, "Vous avez déjà un compte")
    else:
        form = AddUserForm()
    return render(request, 'register.html', context)

Documents/aoomuki competences version 3/app_competences/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Page Title - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
                                        <form>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                <input class="form-control py-4" id="inputEmailAddress" type="email" placeholder="Enter email address" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Password</label>
                                                <input class="form-control py-4" id="inputPassword" type="password" placeholder="Enter password" />
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" id="rememberPasswordCheck" type="checkbox" />
                                                    <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                                </div>
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="password.html">Forgot Password?</a>
                                                <a class="btn btn-primary" href="index.html">Login</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

Documents/aoomuki competences version 3/app_competences/templates/password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Page Title - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Password Recovery</h3></div>
                                    <div class="card-body">
                                        <div class="small mb-3 text-muted">Enter your email address and we will send you a link to reset your password.</div>
                                        <form>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                <input class="form-control py-4" id="inputEmailAddress" type="email" aria-describedby="emailHelp" placeholder="Enter email address" />
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="login.html">Return to login</a>
                                                <a class="btn btn-primary" href="login.html">Reset Password</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

Documents/aoomuki competences version 3/app_competences/templates/register.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Dashboard</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>


            <div class="text-center text-success " >
                {% if messages %}
                    {% for message in messages %}
                        <h3>{{ message }}</h3>
                    {% endfor %}
                {% endif %}
            </div> 
            {% comment %} <div class="col-md-10 offset-1 mb-5" >
                    <form action="{% url 'matrice:Enregistrement'  %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy}}
                    <button type="submit" class="btn btn-secondary btn-sm">Créer le compte</button>
                    </form>
            </div> {% endcomment %}
            <div class="col-md-10 offset-1 mb-5" >
            <form method="POST" action="">
                {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{form.last_name.errors}}
                    {% comment %} {{form.last_name.label_tag}} {% endcomment %}
                    {{form.last_name|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.first_name.errors}}
                    {% comment %} {{form.first_name.label_tag}} {% endcomment %}
                    {{form.first_name|as_crispy_field}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{form.email.errors}}
                    {% comment %} {{form.email.label_tag}} {% endcomment %}
                    {{form.email|as_crispy_field}}
                </div>
            </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.society.errors}}
                    {% comment %} {{form.email.label_tag}} {% endcomment %}
                    {{form.society|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.workstation.errors}}
                    {% comment %} {{form.email.label_tag}} {% endcomment %}
                    {{form.workstation|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.is_collaborater.errors}}
                    {% comment %} {{form.email.label_tag}} {% endcomment %}
                    {{form.is_collaborater|as_crispy_field}}
                </div>
                 <div class="form-field">
                    {{form.is_superuser.errors}}
                    {% comment %} {{form.is_superuser.label_tag}} {% endcomment %}
                    {{form.is_superuser|as_crispy_field}}
                </div>
                <div class="form-field">
                    {% comment %} {{form.is_staff.errors}} {% endcomment %}
                    {% comment %} {{form.is_staff.label_tag}} {% endcomment %}
                    {{form.is_staff|as_crispy_field}}
                </div>

                <div class="form-field">
                    {{form.password1.errors}}
                    {% comment %} {{form.password1.label_tag}} {% endcomment %}
                    {{form.password1|as_crispy_field}}
                </div>
                <div class="form-field">
                    {{form.password2.errors}}
                    {% comment %} {{form.password2.label_tag}} {% endcomment %}
                    {{form.password2|as_crispy_field}}
                </div>

                <hr>
                <button type="submit" name="btnform1" class="save btn btn-secondary">VALIDER</button>

            </form>
            </div> 

                    </div>
                </main>

{% endblock%}